[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "whis-cli"
version = "0.1.0.dev0"
description = "A tiny Linux command whisperer that suggests shell commands based on natural language."
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.8"

authors = [
  { name = "Milan Slesarik", email = "milslesarik@gmail.com" }
]

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: POSIX :: Linux",
    "Environment :: Console",
    "Topic :: Utilities",
]

dependencies = [
  "openai",
  "ollama",
  "pyperclip"  # clipboard management
]

[project.scripts]
whis = "whis.__main__:main"

[project.urls]
Homepage = "https://github.com/milano-slesarik/whis"
"Bug Tracker" = "https://github.com/milano-slesarik/whis/issues"

[tool.setuptools]
packages = { find = { include = ["whis*"] } }

[tool.setuptools.package-data]
whis = ["config.template.toml"]

[project.optional-dependencies]
dev = [
  "dotenv",
  "pytest",
  "pytest-cov",
  "black",
  "ruff",
  "pre-commit>=4.3.0,<5"

]

[tool.black]
line-length = 120
target-version = ["py312"]

[tool.ruff]
line-length = 120

[tool.pytest.ini_options]
addopts = "-q --cov=whis --cov-report=term-missing --cov-report=xml  --cov-fail-under=80"

[tool.coverage.run]
branch = true
source = ["whis"]

[tool.coverage.report]
skip_empty = true
show_missing = true
