[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "whis-cli"
version = "0.1.0.dev0"
description = "A tiny Linux command whisperer that suggests shell commands based on natural language."
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.8"

authors = [
  { name = "Milan Slesarik", email = "milslesarik@gmail.com" }
]

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: POSIX :: Linux",
    "Environment :: Console",
    "Topic :: Utilities",
]

dependencies = [
  "openai",
  "ollama",
  "pyperclip"  # clipboard management
]

[project.scripts]
whis = "whis.cli:run_cli"

[project.urls]
Homepage = "https://github.com/milano-slesarik/whis"
"Bug Tracker" = "https://github.com/milano-slesarik/whis/issues"

[tool.setuptools]
packages = { find = { include = ["whis*"] } }

[project.optional-dependencies]
dev = [
  "dotenv",
  "pytest",
  "black",
  "ruff"
]